lpsdir = './lps/';
gredir = './gre3d/';

%% Generate 3D GRE sequence
gre3d_write_seq('dir', gredir, ...
    'N', 128, ...
    'fov', 20, ...
    'fa', 6, ...
    'tr', 15, ...
    'te', 'min', ...
    'Nacs', 32, ...
    'Ry', 2, ...
    'Rz', 2);

%% Convert the 3D GRE scanarchive data to custom h5 file format
% Assumed that the scanarchive file is transferred into the gre directory
safile_gre = [gredir, 'scanarc.h5'];
gre_convert_data(safile_gre, './gre3d.h5');

%% Generate LpS sequence
lps_write_seq('dir', lpsdir, ...
    'N', 100, ...
    'fov', 20, ...
    'fa', 6, ...
    'tr', 62.5, ...
    'nprj', 320);

%% Convert the LpS scanarchive data to custom h5 file format
% Assumed that the scanarchive file is transferred into the lps directory
safile_lps = [lpsdir, 'scanarc.h5'];
lps_convert_data(safile_lps, './lps.h5');